/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MiniappRouteImport } from './routes/miniapp'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'
import { Route as ApiPublicTelegramSweepSchedulesRouteImport } from './routes/api/public/telegram/sweep-schedules'
import { Route as ApiPublicTelegramSweepDeletionsRouteImport } from './routes/api/public/telegram/sweep-deletions'
import { Route as ApiPublicTelegramRegisterWebhookRouteImport } from './routes/api/public/telegram/register-webhook'
import { Route as ApiPublicMiniappApiRouteImport } from './routes/api/public/miniapp/api'

const MiniappRoute = MiniappRouteImport.update({
  id: '/miniapp',
  path: '/miniapp',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTelegramSweepSchedulesRoute =
  ApiPublicTelegramSweepSchedulesRouteImport.update({
    id: '/api/public/telegram/sweep-schedules',
    path: '/api/public/telegram/sweep-schedules',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTelegramSweepDeletionsRoute =
  ApiPublicTelegramSweepDeletionsRouteImport.update({
    id: '/api/public/telegram/sweep-deletions',
    path: '/api/public/telegram/sweep-deletions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTelegramRegisterWebhookRoute =
  ApiPublicTelegramRegisterWebhookRouteImport.update({
    id: '/api/public/telegram/register-webhook',
    path: '/api/public/telegram/register-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMiniappApiRoute = ApiPublicMiniappApiRouteImport.update({
  id: '/api/public/miniapp/api',
  path: '/api/public/miniapp/api',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/miniapp': typeof MiniappRoute
  '/api/public/miniapp/api': typeof ApiPublicMiniappApiRoute
  '/api/public/telegram/register-webhook': typeof ApiPublicTelegramRegisterWebhookRoute
  '/api/public/telegram/sweep-deletions': typeof ApiPublicTelegramSweepDeletionsRoute
  '/api/public/telegram/sweep-schedules': typeof ApiPublicTelegramSweepSchedulesRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/miniapp': typeof MiniappRoute
  '/api/public/miniapp/api': typeof ApiPublicMiniappApiRoute
  '/api/public/telegram/register-webhook': typeof ApiPublicTelegramRegisterWebhookRoute
  '/api/public/telegram/sweep-deletions': typeof ApiPublicTelegramSweepDeletionsRoute
  '/api/public/telegram/sweep-schedules': typeof ApiPublicTelegramSweepSchedulesRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/miniapp': typeof MiniappRoute
  '/api/public/miniapp/api': typeof ApiPublicMiniappApiRoute
  '/api/public/telegram/register-webhook': typeof ApiPublicTelegramRegisterWebhookRoute
  '/api/public/telegram/sweep-deletions': typeof ApiPublicTelegramSweepDeletionsRoute
  '/api/public/telegram/sweep-schedules': typeof ApiPublicTelegramSweepSchedulesRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/miniapp'
    | '/api/public/miniapp/api'
    | '/api/public/telegram/register-webhook'
    | '/api/public/telegram/sweep-deletions'
    | '/api/public/telegram/sweep-schedules'
    | '/api/public/telegram/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/miniapp'
    | '/api/public/miniapp/api'
    | '/api/public/telegram/register-webhook'
    | '/api/public/telegram/sweep-deletions'
    | '/api/public/telegram/sweep-schedules'
    | '/api/public/telegram/webhook'
  id:
    | '__root__'
    | '/'
    | '/miniapp'
    | '/api/public/miniapp/api'
    | '/api/public/telegram/register-webhook'
    | '/api/public/telegram/sweep-deletions'
    | '/api/public/telegram/sweep-schedules'
    | '/api/public/telegram/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MiniappRoute: typeof MiniappRoute
  ApiPublicMiniappApiRoute: typeof ApiPublicMiniappApiRoute
  ApiPublicTelegramRegisterWebhookRoute: typeof ApiPublicTelegramRegisterWebhookRoute
  ApiPublicTelegramSweepDeletionsRoute: typeof ApiPublicTelegramSweepDeletionsRoute
  ApiPublicTelegramSweepSchedulesRoute: typeof ApiPublicTelegramSweepSchedulesRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/miniapp': {
      id: '/miniapp'
      path: '/miniapp'
      fullPath: '/miniapp'
      preLoaderRoute: typeof MiniappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/sweep-schedules': {
      id: '/api/public/telegram/sweep-schedules'
      path: '/api/public/telegram/sweep-schedules'
      fullPath: '/api/public/telegram/sweep-schedules'
      preLoaderRoute: typeof ApiPublicTelegramSweepSchedulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/sweep-deletions': {
      id: '/api/public/telegram/sweep-deletions'
      path: '/api/public/telegram/sweep-deletions'
      fullPath: '/api/public/telegram/sweep-deletions'
      preLoaderRoute: typeof ApiPublicTelegramSweepDeletionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/register-webhook': {
      id: '/api/public/telegram/register-webhook'
      path: '/api/public/telegram/register-webhook'
      fullPath: '/api/public/telegram/register-webhook'
      preLoaderRoute: typeof ApiPublicTelegramRegisterWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/miniapp/api': {
      id: '/api/public/miniapp/api'
      path: '/api/public/miniapp/api'
      fullPath: '/api/public/miniapp/api'
      preLoaderRoute: typeof ApiPublicMiniappApiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MiniappRoute: MiniappRoute,
  ApiPublicMiniappApiRoute: ApiPublicMiniappApiRoute,
  ApiPublicTelegramRegisterWebhookRoute: ApiPublicTelegramRegisterWebhookRoute,
  ApiPublicTelegramSweepDeletionsRoute: ApiPublicTelegramSweepDeletionsRoute,
  ApiPublicTelegramSweepSchedulesRoute: ApiPublicTelegramSweepSchedulesRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
